version: '2.1'
services:
  inception:
    image: tensorflow/serving:2.1.0-rc1
    volumes:
      - ./inception:/models/inception
    environment:
      - MODEL_NAME=inception
    ports:
      - "8501:8501"
    networks:
        appnet:
            ipv4_address: 172.18.18.04
  yolov3:
    image: tensorflow/serving:2.1.0-rc1
    volumes:
      - ./yolov3:/models/yolov3
    environment:
      - MODEL_NAME=yolov3
    ports:
      - "8502:8501"
    networks:
        appnet:
            ipv4_address: 172.18.18.05
  flask:
    image: june3471/tensorflow_api
    volumes:
      - ./data:/tmp/
      - ./code:/mnt/
    ports:
      - "5000:5000"
    environment:
      - inception_ip=172.18.18.04
      - yolov3_ip=172.18.18.05
    command: python3 mnt/app.py
    networks:
        appnet:
            ipv4_address: 172.18.18.03
networks:
    appnet:
        ipam:
            driver: default
            config:
            - subnet: 172.18.18.0/24
              gateway: 172.18.18.1